name: Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy
      run: |
        echo TBD with key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} ...
