name: Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy zones-splitter
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/videoparking/zones-splitter/actions/workflows/deploy.yml/dispatches -d '{"ref":"main"}' -u ${{ secrets.ZONES_SPLITTER_WORKFLOW_AUTH }}

