name: Validation

on: push

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Zones validation
      run: |
        grep modified -R v1 && exit 2
        echo done
